# Generated by Django 3.0.5 on 2020-04-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lends.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookLend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField()),
                ('return_date', models.DateField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lends.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('books_lent', models.ManyToManyField(through='lends.BookLend', to='lends.Book')),
            ],
        ),
        migrations.AddField(
            model_name='booklend',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lends.Client'),
        ),
    ]
