# Generated by Django 3.0.5 on 2020-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lends', '0002_auto_20200412_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklend',
            name='lend_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booklend',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
