# Generated by Django 3.0.5 on 2020-04-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lends', '0003_auto_20200412_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
