# Generated by Django 3.0.5 on 2020-04-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lends', '0004_book_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='lend_price',
        ),
    ]
